name: Telegram Bot CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'Telega_bot.py'  # Триггер при изменении основного файла
      - 'TelegramBotRecipe.json'
  workflow_dispatch:

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/RecipeApp/RecipeApp/ACTUAL__Build_compose/TelegramBot

    steps:
      # 1. Получаем код
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Проверка файлов
      - name: Verify files
        run: |
          echo "Файлы в репозитории:"
          ls -la
          [ -f Telega_bot.py ] || { echo "ERROR: Telega_bot.py not found!"; exit 1; }

      # 3. Настройка SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 4. Копируем только нужные файлы
      - name: Sync Files
        run: |
          rsync -avz \
                -e "ssh -o StrictHostKeyChecking=no" \
                Telega_bot.py \
                TelegramBotRecipe.json \
                ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.REMOTE_DIR }}/

      # 5. Пересобираем бота
      - name: Rebuild Bot
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
                cd /home/RecipeApp/RecipeApp/ACTUAL__Build_compose
                docker-compose up -d --build telegram_bot
                docker image prune -f
          EOF