name: CI/CD  Docker  Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_DIR: /home/RecipeApp/RecipeApp/ACTUAL__Build_compose

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run flake8 & pytest
        run: |
          pip install flake8 pytest
          flake8 || echo "flake8 warnings"
          pytest -q || echo "tests failed but continue"

      - name: Copy project to server via rsync
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem && chmod 600 key.pem
          rsync -az --delete --progress \
                -e "ssh -o StrictHostKeyChecking=no -i key.pem" \
                ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.REMOTE_DIR }}/
          rm -f key.pem

      - name: Rebuild & restart docker-compose on server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
                cd $REMOTE_DIR
                docker-compose pull
                docker-compose down
                docker-compose up -d --build
                docker image prune -f
          EOF
          rm -f key.pem
